### PR TITLE
[#10] screenshot on test failure

### LINKED ISSUE #10: Capture screenshot on test failure
The goal of this task is to implement functionality to capture and store the screenshot, once the test fails.

### PR DESCRIPTION
**Pull request by N0081K**
resolves #10 
I am not really fully satisfied with this solution but with test life cycle where we do quit browser in aftereach we cannot use testwatcher and I did always use TestNG so I do not know the better way how to do it in JUnit5 than this. Feel free to recommend some better solution.

@socker01 check it 🙏

### CODE REVIEW

File: src/test/java/cz/czechitas/automation/extension/ScreenshotOnFailExtension.java [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+            File screenshotFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
+            try {
+                String SCREENSHOT_DIRECTORY = "failedScreenshots/";
+                FileUtils.copyFile(screenshotFile, new File(SCREENSHOT_DIRECTORY + context.getDisplayName() + ".png"));
+            } catch (IOException e) {
+                System.out.println("Could not save taken screenshot: " + e);
+            }
+        }
+
+        throw cause; // Re-throw the exception to allow JUnit to handle it
```
Comment (socker01) [inline src/test/java/cz/czechitas/automation/extension/ScreenshotOnFailExtension.java:34]: This comment is not necessary from my point of view.

File: src/test/java/cz/czechitas/automation/extension/ScreenshotOnFailExtension.java [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+    }
+
+    @Override
+    public void handleTestExecutionException(ExtensionContext context, Throwable cause) throws Throwable {
+
+        if (driver != null) {
+            File screenshotFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
+            try {
+                String SCREENSHOT_DIRECTORY = "failedScreenshots/";
+                FileUtils.copyFile(screenshotFile, new File(SCREENSHOT_DIRECTORY + context.getDisplayName() + ".png"));
```
Comment (socker01) [inline src/test/java/cz/czechitas/automation/extension/ScreenshotOnFailExtension.java:28]: What if there is already exists screenshot with the same name? Don't we want to put a timestamp into the filename?

**Review by socker01 — APPROVED** [review]
